apiVersion: v1
kind: Secret
metadata:
  name: hiddensecret
data:
  .pass: cGFzcwo=
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      run: busybox
  template:
    metadata:
      labels:
        run: busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        args: ["sleep", "3600"]
        env:
          - name: SECRET_PASS
            valueFrom:
              secretKeyRef:
                name: hiddensecret
                key: .pass 

