#This mounts the service token as a secret, I created this spec to query the api with the bearer token
apiVersion: v1
kind: Pod
metadata:
  name: mytestauthz
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sleep","2600"]
    volumeMounts:
    - name: tmpadm
      mountPath: "/var/run/secrets/kubernetes.io/serviceaccount/token"
  volumes:
   - name: tmpadm
     secret:
       secretName: tmpadm-token-x4sfr
