apiVersion: v1
kind: Pod
metadata:
   name: mypod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: mygcevol
        mountPath: /test
  volumes:
     - name: mygcevol
       persistentVolumeClaim:
         claimName: pvcgc
