#the vol by name disk-1 should be created before
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypvgc
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gcecentraliowa
  gcePersistentDisk:
    fsType: ext4
    pdName: disk-1
