---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    pods: "1"
    requests.cpu: "2"
    limits.cpu: "6"
    configmaps: "3"
    services: "2"
    persistenntvolumeclaims: "1"
