#EmptyDir is a Pod-scoped concept. Every pod gets its own EmptyDir volume, and all containers inside the Pod can mount that volume
#This is useful for multicontainer pods, however this will not work with deployment spec
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis
spec:
  containers:
  - image: redis
    name: redis
    volumeMounts:
    - name: emp
      mountPath: /tmp
  volumes:
    - name: emp
      emptyDir: {}
  restartPolicy: Never
