apiVersion: v1
kind: ConfigMap
metadata:
  name: config1
data:
  app: mongodump
---  
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis
spec:
  containers:
  - image: redis
    name: redis
    volumeMounts:
      - name: configmap
        mountPath: /tmp
  restartPolicy: Never
  volumes:
    - name: configmap
      configMap:
        name: config1
