apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    metadata:
       labels:
          app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: test
              mountPath: /tmp
      volumes:
        - name: test
          persistentVolumeClaim:
            claimName: pvc-nfs
  replicas: 3
  selector:
    matchLabels:
      app: nginx   
