---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name:  busybox
  labels:
    type: web
spec:
  template:
     metadata:
       name: busybox
       labels:
         type: web
     spec:
       containers:
         - image: busybox
           name: busybox
           command:
           - sleep
           - "3600"
  replicas: 2
  selector:
    matchLabels:
       type: web
