apiVersion: batch/v1
kind: Job
metadata:
   name: py-job
spec:
  completions: 3
  backoffLimit: 10 #This is so the job does not quit before it succeeds
  template:
    spec:
      containers:
        - name: python-job
          image: torg.jfrog.io/test-pyrun:1314
          command: ["python3", "-m", "unittest", "test_sanity.py"]
      restartPolicy: Never 
