#kubectl run --generator=run-pod/v1 nginx --image-nginx -o yaml --export --dry-run
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
