#kubectl create configmap config1 --from-literal=env=dev --dry-run -o yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config1
data:
  env: dev
  tier: backend
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    envFrom:
      - configMapRef:
          name: config1
    env:
      - name: ROLE
        valueFrom:
          configMapKeyRef:
            name: config1
            key: tier
  restartPolicy: Never
