---
apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    type: backend
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  #sessionAffinity: ClientIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    type: backend
