---
apiVersion: v1
kind: Pod
metadata:
  name: djangoapp-pod
spec:
  containers:
    - name: djangoapp-pod
      image: houami/djangoapp:v1
      ports:
        - name: http
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: djangoapp-svc
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    name: djangoapp-pod
