---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  ports:
  - port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: myservice
subsets:
  - addresses:
    - ip: 172.17.0.2
    - ip: 172.17.0.3
    ports:
    - port: 80 # target port
