---
apiVersion: v1
kind: Service
metadata:
  name: couchbasedb
spec:
  type: ExternalName
  externalName: couchbasedb.wm.com
# for port remapping
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
