kind: Pod
apiVersion: v1
metadata:
  name: app1-app
  labels:
    app: app1
spec:
  containers:
    - name: app1-app
      image: hashicorp/http-echo
      args:
        - "-text=app1"

---

kind: Service
apiVersion: v1
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
    - port: 5678 # Default port for image

