#Create a network policy to allow traffic from the 'Internal' application only to the 'payroll-service' and 'db-service' You might want to enable ingress traffic to the pod to test your rules in the UI.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internal-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      name: internal
  policyTypes:  
  - Egress
  - Ingress
  ingress:
    - {} #Empty ingress rule ({}) allows traffic from all pods in the current namespace, as well as other namespaces
  egress:
  - to:
    - podSelector:
        matchLabels:
          name: mysql
    ports:
    - protocol: TCP
      port: 3306

  - to:
    - podSelector:
        matchLabels:
          name: payroll
    ports:
    - protocol: TCP
      port: 8080
