apiVersion: v1
kind: Pod
metadata:
  name: nginxserver
  labels:
    app: secure-app
    setaccess: "true"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: curlclient
spec:
  containers:
  - name: busybox
    image: radial/busyboxplus:curl
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
---
apiVersion: extensions/v1beta1 
kind: NetworkPolicy
metadata:
  name: mynwpol
spec:
  podSelector:
    matchLabels:
      setaccess: "true"
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from: 
      - podSelector:
          matchLabels:
            setaccess: "true"
      ports:
        - port: 80
  egress:
    - to:
      - podSelector:
          matchLabels:
            setaccess: "true"
      ports:
        - port: 80
