apiVersion: v1
kind: LimitRange
metadata:
  name: "mylimit"
spec:
  limits:
  -
    type: Pod
    max: 
      cpu: 2
      memory: 1Gi
    min:
      cpu: 1
      memory: 10Mi
  -
    type: Container
    max:
      cpu: 2
      memory: 1Gi
    min:
      cpu: 0.5
      memory: 5Mi
    default:
      cpu: 2
      memory: 100Mi
