---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-controller
spec:
  template:
    metadata:
      labels:
        name: nginx-controller
    spec:
      containers:
        - name: nginx-controller
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.21.0
          args:
            - /nginx-ingress-controller
  replicas: 1
  selector:
    matchLabels:
      name: nginx-controller
