---
apiVersion: v1
kind: Service
metadata:
  name: couchbasedb
spec:
  ports:
  - port: 8091
    targetPort: 8091
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: couchbasedb
subsets:
  - addresses:
    - ip: 172.17.0.2
    - ip: 172.17.0.3
    ports:
    - port: 8091 # target port
