---
apiVersion: v1
kind: Binding
metadata:
  name: redis
target:
  apiVersion: v1
  kind: Node
  name: node1

#kubectl create -f binding.yaml -o json --dry-run
#curl --header "Content-Type:application/json" --request POST --data { "apiVersion": "v1", "kind": "Binding", "metadata": { "name": "redis", "namespace": "default" }, "target": { "apiVersion": "v1", "kind": "Node", "name": "node1" } } http://$SERVER/api/v1/namespaces/default/pods/$PODNAME/binding

