apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
      matchLabels:
        name: fluentd
  template:
    metadata:
      labels:
        name: fluentd 
    spec:
      containers:
      - name: fluentd
        image: gcr.io/google-containers/fluentd-elasticsearch:v2.4.0
