---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts: 
    - name: nfstest
      mountPath: /test
  volumes:
  - name: nfstest
    persistentVolumeClaim:
      claimName: pvc-nfs-pv1
