---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts: 
    - name: gcetest
      mountPath: /test
  volumes:
  - name: gcetest
    persistentVolumeClaim:
      claimName: mypvc

